[package]
name = "risc0_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.0.1", default-features = false, features = ['std'] }
risc0-core = { version = "0.1.0", path = "../../core" }
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
